apiVersion: v1
kind: Service
metadata:
  name: hello-world
  annotations:
  # create automatic httos end point with elb with https protoclol
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <arn:aws:acm:<your Certificaion>>
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-world